### ISSUE TITLE
Chapter 2 exercise 4 files don't run and fail to build

### ISSUE THREAD

**Issue by mjmarcum** [PacktPublishing/Developing-Solutions-for-Microsoft-Azure-AZ-204-Exam-Guide-2nd-Edition#15]
error CS1061: 'ILoggingBuilder' does not contain a  
definition for 'AddAzureWebAppDiagnostics' and no accessible extension method 'AddAzureWebAppDiagnos 
tics' accepting a first argument of type 'ILoggingBuilder' could be found (are you missing a using d 
irective or an assembly reference?) [C:\Users\Michael\dev\AZ204\Developing-Solutions-for-Microsoft-A 
zure-AZ-204-Exam-Guide-2nd-Edition\Chapter02\02-appsettings-logging\appsettings-logging.csproj]      
    0 Warning(s)
    1 Error(s)

**Comment by pandiculator** [comment]
Remove (or comment out) the line:
```CSharp
builder.Logging.AddAzureWebAppDiagnostics();
```
That worked for me.

**Comment by paul-msft** [comment]
Somehow the relevant package got removed in the repo code, which has now been added, so this now works. Thank you for reporting the issue.
